### ISSUE TITLE
Parameters within the Path section need to require specification of data type

### ISSUE THREAD

**Issue by ckriley** [booknds/sge#13]
Currently the Path section does not require specifying a data type for parameter. This causes a failure in validation within SwaggerHub.

**Comment by EricHenry** [comment]
fixed in PR [#24](https://github.com/booknds/sge/pull/24). Need second pair of eyes to test.

**Comment by EricHenry** [comment]
updated fix in PR [#25](https://github.com/booknds/sge/pull/25)
