### ISSUE TITLE
Support SwaggerHub open / save within SGE

### ISSUE THREAD

**Issue by ckriley** [booknds/sge#2]
Support the ability to load and save to SwaggerHub using a user's credentials / OAuth2 key.

**Comment by ckriley** [comment]
Confirmed the base functionality works in Development. Only issue is that the Cancel button does not close the Save dialog.

**Comment by EricHenry** [comment]
needs to be checked via #41

**Comment by ckriley** [comment]
Confirmed that this works with hkmconsultingllc swagger hub endpoint on both load and save.

**Comment by EricHenry** [comment]
fixed with #41
