### ISSUE TITLE
Update the Consumes / Produces MIME Type selection to include common types

### ISSUE THREAD

**Issue by ckriley** [booknds/sge#42]
The Consumes/Produces should include the following:
- application/xml
- application/atom+xml
- application/json
- application/x-www-form-urlencoded
- text/plain
- text/xml

and/or allow for entering the specific MIME type. There are numerous vendor specific types, image types etc.

**Comment by ckriley** [comment]
Tested in Dev and works appropriately.

**Comment by EricHenry** [comment]
fixed in #47
